Update eks redis
knowledgesystems/knowledgesystems-k8s-deployment pull request #160
Opened 2023-06-20 14:43 UTC by dippindots

2023-06-20 18:17 UTC, zhx828 requested changes
- Depends on your setup, I would recommend using redis-cluster at one point to provide HA. 
- Are you going to get rid of https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/tree/master/cbioportal folder

2023-06-20 18:17 UTC, zhx828 commented on public-eks/cbioportal-prod/redis/README.md
> +| helm          | 3.6.0+  |
We use 3.5.2 in cluster if that matters.

2023-06-20 18:17 UTC, zhx828 commented on public-eks/cbioportal-prod/redis/README.md
> +* the current version of helm which is used at msk for this deployment in our internal kubernetes cluster is v3.6.0 - if you are creating or upgrading the internal cluster deployment, use this versio
I'm a bit confused here. 3.5.2 is helm version we used https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/tree/master/public-eks/cbioportal-prod/shared-services/ingress

Not sure it's necessary to mention internal k8s cluster, and you are referring to msk cluster?

2023-06-20 18:17 UTC, zhx828 commented on public-eks/cbioportal-prod/redis/README.md
> +helm install cbioportal-redis -f cbioportal/redis/cbioportal_redis.yaml --version 12.8.3 --set auth.password=picksomeredispassword oci://registry-1.docker.io/bitnamicharts/redis
Curious why we need to specify `oci`

2023-06-20 18:17 UTC, zhx828 commented on public-eks/cbioportal-prod/redis/README.md
> +* the public cluster has a dedicated instance group named 'mission-critical' which is specified in the nodeSelector argument for the public cluster and a taint toleration for 'dedicated: mission-crit
```suggestion
* the public cluster has a dedicated node group named 'mission-critical' which is specified in the nodeSelector argument for the public cluster and a taint toleration for 'dedicated: mission-critical' is also specified.
```

2023-06-20 18:17 UTC, zhx828 commented on public-eks/cbioportal-prod/redis/README.md
> +helm install cbioportal-genie-persistence-redis -f public-eks-cluster/redis/cbioportal_redis_replica.yaml --version 17.11.6 --set auth.password=picksomeredispassword oci://registry-1.docker.io/bitnam
The README already located in the redis folder, should we use `
helm install cbioportal-genie-persistence-redis -f ./cbioportal_redis_replica.yaml`

2023-06-20 18:17 UTC, zhx828 commented on public-eks/README.md
> +- Make sure the latest aws-cli is installed, the current version of aws used at the time is 2.9.15
We probably should stick to a particular aws-cli version too,

2023-06-20 18:17 UTC, zhx828 commented on public-eks/README.md
> +        aws --region us-east-1  eks update-kubeconfig  --name cbioportal-prod --role-arn arn:aws:sts::070278699608:role/eks-admin --profile [PROFILE]
```suggestion
        aws --region us-east-1  eks update-kubeconfig  --name cbioportal-prod --role-arn arn:aws:sts::ACCOUNT_ID:role/eks-admin --profile [PROFILE]
```

2023-06-20 18:23 UTC, averyniceday commented on public-eks/cbioportal-prod/redis/README.md
> +* the public cluster has a dedicated instance group named 'mission-critical' which is specified in the nodeSelector argument for the public cluster and a taint toleration for 'dedicated: mission-crit
Just a headsup, I don't think we have a mission-critical nodegroup set up in the eks cluster yet, just to remember to either migrate those nodes or create the ndoegroup

2023-06-20 18:25 UTC, averyniceday commented on public-eks/cbioportal-prod/redis/README.md
> +helm install cbioportal-genie-persistence-redis -f public-eks-cluster/redis/cbioportal_redis_replica.yaml --version 17.11.6 --set auth.password=picksomeredispassword oci://registry-1.docker.io/bitnam
Maybe genericize this section? worried someone might just run this command directly and install another genie persistence redis

2023-06-20 18:28 UTC, averyniceday commented
also maybe add redis subfolder  to under the shared services section

2023-06-20 18:41 UTC, dippindots commented on public-eks/cbioportal-prod/redis/README.md
> +helm install cbioportal-redis -f cbioportal/redis/cbioportal_redis.yaml --version 12.8.3 --set auth.password=picksomeredispassword oci://registry-1.docker.io/bitnamicharts/redis
I'm referring to the official documentation in the bitnami helm chart: https://github.com/bitnami/charts/tree/main/bitnami/redis#installing-the-chart

2023-06-20 18:43 UTC, dippindots commented on public-eks/cbioportal-prod/redis/README.md
> +* the public cluster has a dedicated instance group named 'mission-critical' which is specified in the nodeSelector argument for the public cluster and a taint toleration for 'dedicated: mission-crit
@averyniceday I think we might need this `nodegroup` in the eks cluster. If there is no reason to keep the old cluster, we should create a ticket for the whole migration procedure.

2023-06-20 18:45 UTC, dippindots commented on public-eks/README.md
> +- Make sure the latest aws-cli is installed, the current version of aws used at the time is 2.9.15
Should I just say: use version `2.9.15`?

2023-06-21 16:37 UTC, dippindots commented on public-eks/cbioportal-prod/redis/README.md
> +| helm          | 3.6.0+  |
changed to 3.5.2

2023-06-21 16:44 UTC, dippindots commented on public-eks/cbioportal-prod/redis/README.md
> +* the current version of helm which is used at msk for this deployment in our internal kubernetes cluster is v3.6.0 - if you are creating or upgrading the internal cluster deployment, use this versio
Deleted those two notes since they are not necessary, and added the chart version and app version into the table.

2023-06-21 16:45 UTC, dippindots commented on public-eks/cbioportal-prod/redis/README.md
> +* the public cluster has a dedicated instance group named 'mission-critical' which is specified in the nodeSelector argument for the public cluster and a taint toleration for 'dedicated: mission-crit
removed this note too

2023-06-21 16:47 UTC, dippindots commented on public-eks/cbioportal-prod/redis/README.md
> +helm install cbioportal-redis -f cbioportal/redis/cbioportal_redis.yaml --version 12.8.3 --set auth.password=picksomeredispassword oci://registry-1.docker.io/bitnamicharts/redis
Changed to `bitnami/redis`

2023-06-21 17:07 UTC, dippindots commented
@zhx828 @averyniceday Could you take another look? Just addressed all the comments

2023-06-21 17:16 UTC, zhx828 requested changes

2023-06-21 17:16 UTC, zhx828 commented on public-eks/README.md
> +- Make sure the aws-cli and k8s is using desired version
Maybe use numbered list instead of bullet list?

2023-06-21 17:16 UTC, zhx828 commented on public-eks/cbioportal-prod/shared-services/redis/cbioportal_redis.yaml
> +  debug: false
The values file probably should only include the changes to the default?

2023-06-22 04:27 UTC, dippindots commented on public-eks/README.md
> +- Make sure the aws-cli and k8s is using desired version
Changed to numbered list

2023-06-22 04:27 UTC, dippindots commented on public-eks/cbioportal-prod/shared-services/redis/cbioportal_redis.yaml
> +  debug: false
Removed unnecessary values

2023-06-22 04:28 UTC, dippindots commented
@zhx828 Thanks for your review again, just addressed all new comments

2023-06-22 13:58 UTC, zhx828 approved these changes
LGTM. hank you!

2023-06-30 20:22 UTC, dippindots commented
@averyniceday @zhx828 I'm going to merge this pull request, @averyniceday let me know if you want me to make some follow-up changes.

2023-07-04 14:09 UTC, merged